### ISSUE TITLE
Update intermine_builder to handle an already built mine

### ISSUE THREAD

**Issue by heralden** [intermine/intermine_boot#12]
This would require a PR to https://github.com/intermine/docker-intermine-gradle, and probably this repository as well.

intermine_builder is a docker container you can find in the folder of the same name, in the repository linked above. Right now it will build an InterMine instance from scratch every time, but we want it to handle a previously built mine on which it will only run `./gradlew cargoDeployRemote` to deploy to the tomcat docker container.

The already built mine will be present in `$XDG_DATA_HOME/intermine_boot/docker/data/mine/biotestmine` (on Linux this is `~/.local/share/intermine_boot`). Currently, intermine_boot will delete the *docker* folder if it already exists, to start from scratch, so this behaviour will have to be changed to handle this new usecase.

In the future, we will also want to support building a mine saved as an archive, but that isn't a requirement for this issue.

You can start working on this issue immediately without waiting to be assigned (but please add a comment), even if someone has commented before you. We've decided to not assign issues and allow anyone interested to submit a PR. Obviously we won't be able to merge all the PRs, so don't worry about being first. All PRs whether merged or not, will be part of our evaluation of an intern.

It would also be great if you could explain your approach and rationale in the PR description. This only needs to be as long or as in depth as you feel it needs to be for the specific task.

**Comment by 22PoojaGaur** [comment]
Hi, I am taking up this issue!

**Comment by 22PoojaGaur** [comment]
Hi @uosl 

I was looking through the code for changes and I came across following observations -
1.)
The script (build.sh) already checks for existing mine [here](https://github.com/intermine/docker-intermine-gradle/blob/a631235c95e5407d9ba928504217c276e319a1d7/intermine_builder/build.sh#L37)

In a similar fashion other files are only downloaded if they don't already exist.

After that it runs `psql` commands and the buildUserDB.

So, we interfere here and put a check so that psql commands and user database is not rebuilt in every condition.

2)
The docker file (intermine_builder.Dockerfile) which downloads required software and sets environment variable. We put a check there somehow to see if mine is already build and don't run the command to build.

Are my observations correct?
If yes, Which of them should I look at?

**Comment by heralden** [comment]
Hello @22PoojaGaur.
1. That check is just one conditional branch; there are additional ones which would still do unwanted things if the mine were to already exist. I think the safest solution would be to simply run `./gradlew cargoDeployRemote` and then exit the script, for a previously built mine. You can replace the true branch of that conditional with the above.

2. This isn't necessary, and it won't work either since the docker container is prebuilt and fetched from dockerhub.

Remember in addition to this, it also needs to be handled in intermine_boot, as currently it will simply delete the directory and start from scratch. This is a bit more difficult, since you'll need to record what kind of build was done and save it to a file (eg. what Git URL and branch was used to build InterMine, as well as the commit hash so a rebuild can be forced if there's changes). This way, if the user does `intermine_boot start local --build-im --im-branch bluegenes`, it would only start the previously built mine if that was built using the same bluegenes branch, and there hasn't come any new commits since; otherwise it would build from scratch.

**Comment by 22PoojaGaur** [comment]
created pull request 1/2 at https://github.com/intermine/docker-intermine-gradle/pull/9
working on pull request 2/2 to resolve the issue.

**Comment by 22PoojaGaur** [comment]
Created another pull request #21 to handle 2/2

**Comment by 22PoojaGaur** [comment]
Hi @uosl, I have created 2 prs to resolve the issue. Please take a look!
