### ISSUE TITLE
Add Travis support

### ISSUE THREAD

**Issue by leoank** [intermine/intermine_boot#4]
## Problem
Intermine boot don't have any CI support yet

## Outline of a Solution
- Add a .travis.yml file.
- Add scripts to run tests

**Comment by shreyagupta30** [comment]
Hi! I would like to work on this issue

**Comment by niveditarufus** [comment]
I would like to work on this issue as well

**Comment by shreyagupta30** [comment]
@leoank can you please specify a little more about scripts to run tests?
Which script is to be used to trigger test?

**Comment by aakankshadhurandhar** [comment]
@leoank I would like to work on this issue

**Comment by heralden** [comment]
Hello all! Due to there being a lot of interest in this project compared to the amount of issues, we've decided to not assign issues and allow anyone interested to submit a PR. Obviously we won't be able to merge all the PRs, so don't worry about being first. All PRs whether merged or not, will be part of our evaluation of an intern.

It would also be great if you could explain your approach and rationale in the PR description. This only needs to be as long or as in depth as you feel it needs to be for the specific task.

**Comment by heralden** [comment]
As a suggestion for a test to run during CI, how about `intermine_boot start local`, then wait up to 15 minutes running `curl http://localhost:9999/biotestmine/service/version` until it returns a successful response (failing if it doesn't finish after the waiting time). You might have to test with Travis CI whether 15 minutes is enough time.

It's possible that this test would be better written in Python, instead of the travis.yml file. In that cause, this applies to #3.

**Comment by leoank** [comment]
@shreyagupta30 look at #3 Try to follow the comments there or better collaborate with someone interested in working on #3 This issue is dependant on that issue.

**Comment by shreyagupta30** [comment]
@leoank I will surely do that. Thanks! :grin:

**Comment by niveditarufus** [comment]
@leoank @uosl 
I have submitted a pull request related to #3 and this issue please review it a let me know if I am on the right track.

**Comment by leoank** [comment]
@niveditarufus @shreyagupta30 added a few suggestions to your PRs

**Comment by heralden** [comment]
Resolved with https://github.com/intermine/intermine_boot/pull/39
